# Generated by Django 4.1.5 on 2023-02-28 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_teacher_delete_choice_delete_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
