# Generated by Django 4.1.5 on 2023-03-01 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
