# Generated by Django 4.1.5 on 2023-03-01 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('demo', '0005_delete_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linked_user', models.CharField(max_length=200)),
                ('yandex_login', models.CharField(max_length=200)),
                ('yandex_password', models.CharField(max_length=200)),
                ('stepik_login', models.CharField(max_length=200)),
                ('stepik_password', models.CharField(max_length=200)),
            ],
        ),
    ]
