# Generated by Django 4.1.5 on 2023-03-27 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0006_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='yandex_password',
        ),
        migrations.AddField(
            model_name='teacher',
            name='yandex_session',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='stepik_login',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='stepik_password',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='yandex_login',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
