# Generated by Django 4.1.5 on 2023-03-27 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0007_remove_teacher_yandex_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linked_teacher', models.CharField(max_length=200)),
                ('tasks', models.JSONField(blank=True)),
            ],
        ),
    ]
