# Generated by Django 4.1.5 on 2023-05-25 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0011_remove_discipline_d_children'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Groups',
            new_name='Group',
        ),
    ]
