# Generated by Django 4.1.5 on 2023-05-26 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0013_disciplinegroup_delete_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplinegroup',
            name='g_table',
        ),
    ]
