# Generated by Django 4.1.5 on 2023-06-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0014_remove_disciplinegroup_g_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplinegroup',
            name='d_owner',
            field=models.CharField(default='admin', max_length=200),
            preserve_default=False,
        ),
    ]
