# Generated by Django 4.1.5 on 2023-06-08 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('demo', '0016_rename_d_owner_disciplinegroup_g_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='s_owner',
            field=models.CharField(default='admin', max_length=200),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ya_session', models.FilePathField(blank=True)),
                ('stepik_key', models.CharField(blank=True, max_length=2000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
