# Generated by Django 4.1.5 on 2023-06-09 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0017_students_s_owner_credentials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='s_name',
        ),
        migrations.AddField(
            model_name='students',
            name='s_display_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='students',
            name='s_stepik_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='students',
            name='s_ya_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='students',
            name='s_email',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
