# Generated by Django 4.1.5 on 2023-06-09 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0018_remove_students_s_name_students_s_display_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Students',
            new_name='Student',
        ),
    ]
