# Generated by Django 4.1.5 on 2023-06-09 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0019_rename_students_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='g_id',
            new_name='d_id',
        ),
    ]
