# Generated by Django 4.1.5 on 2023-06-09 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0020_rename_g_id_student_d_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credentials',
            name='user',
        ),
        migrations.AddField(
            model_name='credentials',
            name='d_owner',
            field=models.CharField(default='admin', max_length=200),
            preserve_default=False,
        ),
    ]
