# Generated by Django 4.1.5 on 2023-06-09 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0021_remove_credentials_user_credentials_d_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credentials',
            old_name='d_owner',
            new_name='user_name',
        ),
    ]
