# Generated by Django 4.1.5 on 2023-06-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0022_rename_d_owner_credentials_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplinegroup',
            name='t_log',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
