# Generated by Django 4.1.5 on 2023-06-11 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0023_disciplinegroup_t_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplinegroup',
            name='t_log',
            field=models.TextField(blank=True),
        ),
    ]
