# Generated by Django 4.1.5 on 2023-06-11 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0024_alter_disciplinegroup_t_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credentials',
            name='ya_session',
        ),
    ]
