# Generated by Django 4.1.5 on 2023-06-11 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0026_credentials_ya_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credentials',
            name='ya_login',
        ),
    ]
