# Generated by Django 4.1.5 on 2023-06-11 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0029_alter_credentials_options_credentials_stepik_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplinegroup',
            name='t_col',
            field=models.IntegerField(default=0),
        ),
    ]
