# Generated by Django 4.1.5 on 2023-06-11 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0030_disciplinegroup_t_col'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplinegroup',
            name='t_col',
            field=models.IntegerField(default=2),
        ),
    ]
