# Generated by Django 4.1.5 on 2023-06-11 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0031_alter_disciplinegroup_t_col'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='s_email',
        ),
    ]
