# Generated by Django 4.1.5 on 2023-06-11 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0032_remove_student_s_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='s_display_name',
        ),
    ]
