# Generated by Django 4.1.5 on 2023-06-12 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0034_importlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImportLog',
        ),
    ]
