# Generated by Django 4.1.5 on 2023-06-12 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0035_delete_importlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_id', models.UUIDField()),
                ('d_id', models.UUIDField()),
                ('g_number', models.IntegerField()),
                ('i_type', models.CharField(max_length=100)),
                ('i_contest', models.IntegerField()),
                ('t_col', models.IntegerField(default=2)),
            ],
        ),
    ]
